export { default as DesktopLayout } from './desktop/desktop-layout.js';
export { default as DesktopHeader } from './desktop/header.js';
export { default as ProfileHeader } from './desktop/profile-header.js';
export { default as DesktopNav } from './desktop/desktop-nav.js';
export { default as AboutPage } from './desktop/about.js';
export { default as BlogPage } from './desktop/blog.js';
export { default as ContactPage } from './desktop/contact.js';
export { default as PortfolioPage } from './desktop/portfolio.js';
export { default as DesktopFooter } from './desktop/desktop-footer.js';